"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_cy#@itz&6u@afm93h%&+vnlyhat%s(j5x*uxh31nplff%2ska'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
# Permitir dominios de Render
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'books',
    'widget_tweaks',
    'mozilla_django_oidc',
]
AUTH_USER_MODEL = 'users.CustomUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mozilla_django_oidc.middleware.SessionRefresh', 
]


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# --- OIDC (Keycloak) Configuration ---

# Reemplaza 'bookswap-realm' si usaste un nombre diferente para tu Realm.
# Reemplaza 'django-client' si usaste un Client ID diferente.
# Pega aquí el Client Secret que obtuviste de Keycloak.

OIDC_RP_CLIENT_ID = "django-client"
OIDC_RP_CLIENT_SECRET = "9g7zITy5SF6K3LZBnNTat25nqsk0v8Nw"  # 

OIDC_OP_AUTHORIZATION_ENDPOINT = "http://localhost:8081/realms/bookswap-realm/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = "http://localhost:8081/realms/bookswap-realm/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = "http://localhost:8081/realms/bookswap-realm/protocol/openid-connect/userinfo"
OIDC_OP_JWKS_ENDPOINT = "http://localhost:8081/realms/bookswap-realm/protocol/openid-connect/certs"
OIDC_OP_LOGOUT_ENDPOINT = "http://localhost:8081/realms/bookswap-realm/protocol/openid-connect/logout"

OIDC_RP_SIGN_ALGO = "RS256"
# URLs a las que Django debe redirigir después del login/logout
LOGIN_URL = "oidc_authentication_init"
LOGIN_REDIRECT_URL = "/"  # Redirige a la página principal después de un login exitoso
LOGOUT_REDIRECT_URL = "/" # Redirige a la página principal después de un logout exitoso

# Añade el backend de autenticación de OIDC
AUTHENTICATION_BACKENDS = (
    'users.authentication.MyOIDCAB',
    'django.contrib.auth.backends.ModelBackend', # Mantén este si usas el admin de Django
)

# Esto crea usuarios en Django automáticamente cuando inician sesión por primera vez vía Keycloak
OIDC_CREATE_USER = True
OIDC_USERNAME_ALGO = lambda email: email # Usa el email como username

# Mapeo de claims (atributos del token) a campos del modelo User de Django
OIDC_RP_CLAIMS_TO_USER_MAPPING = {
    "sub": "username",
    "given_name": "first_name",
    "family_name": "last_name",
    "email": "email",
}